name: Auto Assign Issues to Projects

on:
  issues:
    types:
      - opened

# map fields with customized labels
env:
  todo: Todo ✏️
  done: Done ✅
  in_progress: In Progress 🚧

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Move issue to ALM Accelerator ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v1.1.1
        if: contains(github.event.issue.labels.*.name, 'alm-accelerator')
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          user: mikefactorial
          # organization: sample-org
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
      - name: Move issue to CoE Starter Kit ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v1.1.1
        if: contains(github.event.issue.labels.*.name, 'coe-starter-kit')
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          user: mikefactorial
          # organization: sample-org
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status