name: Auto Assign Issues to Projects

on:
  issues:
    types: [labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign topic to Project
    steps:
    - name: Assign issues with alm-accelerator label to ALM Accelerator Project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: contains(github.event.issue.labels.*.name, 'alm-accelerator')
      with:
        project: 'https://github.com/users/mikefactorial/projects/1'